### PR TITLE
Add Cherokee transliteration

### PR DESCRIPTION
**Pull request by hu-a**
#711 

I've added a Cherokee transliteration IME with unit tests. I believe this addresses some of the [thornier issues of transliterating Cherokee](https://en.wikipedia.org/w/index.php?title=Cherokee_syllabary&oldid=1124646659#Transliteration_issues).

Let me know if you want me to add more tests or fix style.

### CODE REVIEW

**Review by amire80 — CHANGES_REQUESTED** [review]
Hello and happy new year! It's a very nice surprise, thank you!

It mostly looks OK, but I see a few issues. The biggest is the one with the q combinations. The rest are mostly cosmetic.

**Comment by amire80** [comment]
See the detailed review in the code. I also have a few general questions:
What prompted you to do this?
Are you a Cherokee speaker yourself?
Are you in contact with other speakers?
Also, are you familiar with other typing solutions for Cherokee?

**Comment by hu-a** [comment]
Hi, thanks for the review, I will revise the code. To answer your questions, I am not a Cherokee speaker myself and I don't have personal relationships with Cherokee speaking people. I am a PhD student studying, among other things, the use of technology for indigenous language revitalization. I am a Lushootseed (dxʷləšucid) learner and was surprised that Wikipedia had a Lushootseed IME, so I found this project. I had previously studied the history of the Cherokee syllabary and contributed to the Wikipedia article on its creator [Sequoyah](https://en.wikipedia.org/wiki/Sequoyah). 

I was surprised that there was no Cherokee IME considering that [Cherokee has a (small) Wikipedia](https://chr.wikipedia.org/wiki/%E1%8E%A4%E1%8E%B5%E1%8E%AE%E1%8E%B5%E1%8F%8D%E1%8F%97) and there is an active language revitalization movement underway. Although Cherokee keyboards are available on most operating systems, an IME would lower the barrier to contributing to Cherokee Wikipedia because users would not have to install the keyboard _and_ learn a new keyboard layout.

Since it's a syllabary, I was pretty sure that the rules would be straightforward to implement, even though I'm not a speaker. That is, after all, what made the syllabary so successful when it was first introduced. However, if you think it should be tested with Cherokee speakers, I can try to reach out to the language department at the Cherokee Nation to get some people to test it out.

**Review by amire80 — APPROVED** [review]
Thank you! The code functions correctly. I'll correct some minor whitespace issues in another patch.

**Pull request merged**
