### PR TITLE
Update te-transliteration.js

### PR DESCRIPTION
**Pull request by tuxnani**
Added జ్ఞ gunintam

### CODE REVIEW

**Comment by tuxnani** [comment]
I have added two test cases sufficient for the changes I have made. Please let me know if it gets committed. This bug is really confusing comunity members, and there is another discussion today at Village pump on Telugu Wikipedia.

**Comment by tuxnani** [comment]
Also, no need to update documentation, as I have created it keeping in view all consonants. Some more consonants will be added soon into this scheme.

**Comment by tuxnani** [comment]
What is the status on this update?
Can this be merged now with the trunk code? I have done all necessary changes to tests file as well.

**Comment by kartikm** [comment]
@tuxnani As requested in, https://github.com/wikimedia/jquery.ime/pull/369#issuecomment-67731810 relavant test need updates.

**Comment by tuxnani** [comment]
Added tests as a separate pull request. https://github.com/wikimedia/jquery.ime/pull/384

**Comment by amire80** [comment]
Replaced by #508.

**Pull request closed without merging**
