### PR TITLE
Patch for non-joiner errors and full-stop 

### PR DESCRIPTION
**Pull request by Sipun**
some Wikipedians complained about some bugs in transliteration system in Odia Wikimedia projects. Here is the link for Village Pump discussion - https://or.wikipedia.org/wiki/%E0%AC%89%E0%AC%87%E0%AC%95%E0%AC%BF%E0%AC%AA%E0%AC%BF%E0%AC%A1%E0%AC%BC%E0%AC%BF%E0%AC%86:%E0%AC%86%E0%AC%B2%E0%AD%8B%E0%AC%9A%E0%AC%A8%E0%AC%BE_%E0%AC%B8%E0%AC%AD%E0%AC%BE#.E0.AC.93.E0.AC.A1.E0.AC.BC.E0.AC.BF.E0.AC.86_.E0.AC.87.E0.AC.A8.E0.AC.AA.E0.AD.81.E0.AC.9F_.E0.AC.AE.E0.AD.87.E0.AC.A5.E0.AC.A1.E0.AC.BC.E0.AC.B0.E0.AD.87_.E0.AC.AA.E0.AC.B0.E0.AC.BF.E0.AC.AC.E0.AC.B0.E0.AD.8D.E0.AC.A4.E0.AD.8D.E0.AC.A4.E0.AC.A8

I've fixed that issue. accepted by admins.

### CODE REVIEW

**Comment by kartikm** [comment]
Thanks for your pull request. Can you put summary of what was the issue and what has been changed in the patch?

**Comment by Sipun** [comment]
Well major issues were:
1. when someone types 'Diz / Dzi' it appears 'ଡି଼' it should be 'ଡ଼ି' 
2. wA = 'ୱ୍ଆ'   it should be wA = 'ୱା'
3. 'rya =ର୍ୟ'   it should be ର‍୍ୟା
Other minor issue:
 for '।' it is replaced from 'Z' to '.'

**Comment by santhoshtr** [comment]
@kartikm meant to ask to have a good commit message than 'bug fix' - Normally it is one line summary of what you did(look for commit message examples in this repo or just search in web for commit message guidelines). In future if we go through the log of the commit, we should be able to understand what we did. Practically most of commits are bug fixes. So a better commit message is expected.

**Comment by Sipun** [comment]
Sorry for the mistake... I've changed the summary... Is it right ?

**Comment by santhoshtr** [comment]
Well, I was refering the commit message "bug fix" and not the title of the pull request.

**Comment by kartikm** [comment]
@Sipun Can you update commit message as @santhoshtr mentioned? Also, @psubhashish can you help to update this patch?

**Comment by amire80** [comment]
@Sipun, @psubhashish, is this still needed now that #478 is merged?

**Comment by Sipun** [comment]
@amire80  no this is no more required. #478 is the latest modification. Thanks for merging that.

**Pull request closed without merging**
