### PR TITLE
Updates for Norwegian Bokmål

### PR DESCRIPTION
**Pull request by jeblad**
Mostly updates to Norwegian Bokmål, thereby also updates through reuse of Norwegian Nynorsk.
A full update of Norwegian Nynorsk should not be done before there are feedback on the Bokmål version.

This version for Bokmål reuse a common baseform, which provide transliteration of some non-character entities.

### CODE REVIEW

**Comment by jeblad** [comment]
Change  10cfe23 has additional edits to make the cleanup pass. They should have been in a separate change.

**Comment by kartikm** [comment]
Yes, those other commits should go in a separate pull request.

**Comment by jeblad** [comment]
The failures should be fixed in your master, and then the pull should be rebased. There are also failures in ml-inscript, hi-transliteration, and the tests for fa-kbd.

The change set also contains additional updates for the README files as there are undocumented features that hasn't been documented before.

**Comment by jeblad** [comment]
This will need a rebase.

**Comment by jeblad** [comment]
To messy.

**Pull request closed without merging**
