### PR TITLE
added code for ౡ  and corresponding testcase

### PR DESCRIPTION
**Pull request by tuxnani**
added code for ౡ  and corresponding testcase

### CODE REVIEW

**Review by amire80 — APPROVED** [review]

**Comment by kartikm** [comment]
@tuxnani It seems the test is failing for this PR. Can you check it?

**Review by amire80 — CHANGES_REQUESTED** [review]
Sorry, approved by mistake earlier. A test is failing. The rule is probably incorrectly written.

**Comment by srish** [comment]
@tuxnani ping! Would it be possible for you to fix the rule?

**Comment by Nikerabbit** [comment]
I thought it is order dependent, but it is still failing so it's something else.

**Review by srish — APPROVED** [review]

**Pull request merged**
