### PR TITLE
or-OdiScript input method.

### PR DESCRIPTION
**Pull request by majnun1337**
Hello! Requesting to add this input method to the 'or' rules.
Community discussion and consensus: https://goo.gl/TbonxO and http://goo.gl/l39acO
Also, please refer to the following discussion: https://github.com/wikimedia/jquery.ime/pull/402

Thank you.

### CODE REVIEW

**Comment by psubhashish** [comment]
Can anyone please take a look at this and add this?

**Comment by kartikm** [comment]
There are small issues. Please fix it and it should be ready:

[L19:C37] W044: Bad or unnecessary escaping.
['([କ-ହ]୍[କ-ହ])@@', 'ର୍\$1'], //reph

[L20:C31] W044: Bad or unnecessary escaping.
['([କ-ହ])@@', 'ର୍\$1'], //reph

[L25:C17] W044: Bad or unnecessary escaping.
['୍\ ', '୍ '], // ending with halant+zwnj

[L38:C32] W044: Bad or unnecessary escaping.
['([କନପସମ])Q', 'ତ୍\$1' ],

**Comment by kartikm** [comment]
@psubhashish Can you fix above error and resubmit pull request?

**Comment by psubhashish** [comment]
Can you remove these four and submit. Manoj is not available at this moment and there are more changes to be made soon by another contributor as he has found out many new needs.

**Comment by kartikm** [comment]
I'm not sure I can edit other's pull request.

**Pull request merged**
