### PR TITLE
Update jv-keyboard.js

### PR DESCRIPTION
**Pull request by bennylin**
Add common shortcuts, fix bug, change url link

Please merge, because the bug is quite severe, I've asked the bugfix since last year #760 760

### CODE REVIEW

**Comment by srish** [comment]
@bennylin Thanks for this patch! We will review it shortly. In the meantime, could you also create a task on Phabricator around this explaining in a few lines what is the issue this pull request is trying to address? You can then add `LPL Technical Support` tag to the task, assign it to yourself, and share link to this pull request in a comment on the task. TY!

**Review by srish — CHANGES_REQUESTED** [review]
Based on the new characters you added, you might want to expand the test cases here: https://github.com/wikimedia/jquery.ime/blob/596391d29881d08b2495675aade85336e616d928/test/jquery.ime.test.fixtures.js#L2860

**Comment by bennylin** [comment]
Is this a new procedure? Why two places and not centralized here? I have many PR that are waiting for review since last year while collecting dust. Do you want me to create ticket for each of them?
* https://phabricator.wikimedia.org/T373701
* Test added

**Review by srish — APPROVED** [review]
@amire80 I have tested this PR and these changes look good to me. Could you take another look and merge it?

**Comment by srish** [comment]
@bennylin Thanks for creating the task! I requested that it be added to Phabricator so it can be prioritized more effectively. Apologies that your other pull requests haven't received attention. We hope to improve in this area!

**Comment by bennylin** [comment]
Thanks @srish !

**Pull request merged**
