### PR TITLE
Jv translit

### PR DESCRIPTION
**Pull request by bennylin**
Update after 7 years. Fixing bugs typing 'sri', or 'syu'. Thanks for the testers of Javanese Wikipedia editors.

### CODE REVIEW

**Comment by bennylin** [comment]
Can you review this, @santhoshtr? Thanks.

**Comment by santhoshtr** [comment]
Can you please add some tests also? Refer documentation and existing tests.

**Comment by amire80** [comment]
Comment: I'm working with @bennylin on updating this. It will probably be submitted as a new pull request soon.

**Comment by amire80** [comment]
Comment: I plan to get it merged, please don't close it :)

**Comment by bennylin** [comment]
This can be closed. I've submitted a new PR https://github.com/wikimedia/jquery.ime/pull/717

Thanks Amir.

**Pull request closed without merging**
